module Hackage4Nix.Nix.Abs where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
newtype QString = QString String deriving (Eq,Ord,Show)
newtype URL = URL String deriving (Eq,Ord,Show)
newtype Path = Path String deriving (Eq,Ord,Show)
data Expr =
   Expr [Argument] Argument Dictionary
  deriving (Eq,Ord,Show)

data Argument =
   Argument Ident
  deriving (Eq,Ord,Show)

data Dictionary =
   Dictionary [Attribute]
  deriving (Eq,Ord,Show)

data Attribute =
   Attribute Reference Value
  deriving (Eq,Ord,Show)

data Reference =
   Reference [Ident]
  deriving (Eq,Ord,Show)

data Value =
   StringV String
 | QStringV QString
 | URLV URL
 | PathV Path
 | BoolV Boolean
 | AttributeV Reference
 | ListV [Value]
 | DictionaryV Dictionary
 | FunctionV Reference Dictionary
  deriving (Eq,Ord,Show)

data Boolean =
   Yes
 | No
  deriving (Eq,Ord,Show)

