name:           cabal2nix
version:        "2.3.1"
synopsis:       Convert Cabal files into Nix build instructions.
author:
  - Peter Simons
  - Andres Loeh
  - Benno Fünfstück
  - Mateusz Kowalczyk
  - Michael Alan Dorman
  - Mathijs Kwik
  - Shea Levy
  - Dmitry Malikov
  - Eric Seidel
  - Hamish Mackenzie
  - Nikolay Amiantov
  - Aycan iRiCAN
  - Bryan Gardiner
  - Joe Hermaszewski
  - John Wiegley
  - Philipp Hausmann
  - Spencer Janssen
  - Tom Hunger
  - William Casarin
  - koral
  - Adam Vogt
  - Alexey Shmalko
  - Corey O'Connor
  - Cray Elliott
  - Felix Kunzmann
  - Gabriel Ebner
  - Gergely Risko
  - Jacob Mitchell
  - Joachim Fasting
  - John Albietz
  - John Chee
  - Jussi Maki
  - Mark Laws
  - Mark Wotton
  - Matthew Stewart
  - Matvey Aksenov
  - Nicolas Rolland
  - Oliver Charles
  - Pascal Wittmann
  - Patrick John Wheeler
  - Profpatsch
  - Raymond Gauthier
  - Renzo Carbonara
  - Rodney Lorrimar
  - Sibi
  - Tanner Doshier
  - Viktar Basharymau
  - danbst
  - karsten gebbert
  - laMudri
  - Александр Цамутали
maintainer:     Peter Simons <simons@cryp.to>
license:        BSD3
license-file:   LICENSE
github:         nixos/cabal2nix
category:       Distribution, Nix
stability:      stable
tested-with:    GHC > 7.10 && < 8.3
description: >
  Convert Cabal files into Nix build instructions. Users of Nix can install the
  latest version by running:

  .

  > nix-env -i cabal2nix

custom-setup:
  dependencies:
    - base >= 4 && <5
    - Cabal
    - cabal-doctest >= 1 && <1.1

ghc-options: -Wall

extra-source-files:
  README.md

dependencies:
  - aeson
  - ansi-wl-pprint
  - base < 5
  - bytestring
  - Cabal > 1.24
  - containers
  - deepseq >= 1.4
  - directory
  - distribution-nixpkgs >= 1.1
  - filepath
  - hackage-db
  - hopenssl >= 2
  - language-nix
  - lens
  - optparse-applicative
  - pretty >= 1.1.2
  - process
  - split
  - text
  - transformers
  - yaml

library:
  source-dirs: src
  other-extensions:
    - CPP
    - DeriveGeneric
    - FlexibleInstances
    - MultiParamTypeClasses
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
  exposed-modules:
    - Cabal2nix
    - Distribution.Nixpkgs.Fetch
    - Distribution.Nixpkgs.Haskell
    - Distribution.Nixpkgs.Haskell.BuildInfo
    - Distribution.Nixpkgs.Haskell.Constraint
    - Distribution.Nixpkgs.Haskell.Derivation
    - Distribution.Nixpkgs.Haskell.FromCabal
    - Distribution.Nixpkgs.Haskell.FromCabal.Configuration
    - Distribution.Nixpkgs.Haskell.FromCabal.Flags
    - Distribution.Nixpkgs.Haskell.FromCabal.License
    - Distribution.Nixpkgs.Haskell.FromCabal.Name
    - Distribution.Nixpkgs.Haskell.FromCabal.Normalize
    - Distribution.Nixpkgs.Haskell.FromCabal.PostProcess
    - Distribution.Nixpkgs.Haskell.Hackage
    - Distribution.Nixpkgs.Haskell.OrphanInstances
    - Distribution.Nixpkgs.Haskell.PackageSourceSpec

executables:
  cabal2nix:
    main:               Main.hs
    source-dirs:        cabal2nix
    other-modules:
      - Paths_cabal2nix
    dependencies:
      - cabal2nix

  hackage2nix:
    main:               Main.hs
    source-dirs:        hackage2nix
    other-modules:
      - Paths_cabal2nix
      - HackageGit
    dependencies:
      - cabal2nix
      - monad-par
      - monad-par-extras
      - mtl
      - time
      - utf8-string
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  doctests:
    main: doctests.hs
    source-dirs:
      - test
    dependencies:
      - doctest
    ghc-options:
      - -threaded
