{-# LANGUAGE OverloadedStrings #-}

module Distribution.Nixpkgs.Haskell.FromCabal.Name ( toNixName, libNixName, buildToolNixName ) where

import Data.Maybe
import Data.String
import Distribution.Package
import Distribution.Text
import Language.Nix

-- | Map Cabal names to Nix attribute names.
toNixName :: PackageName -> Identifier
toNixName "" = error "toNixName: invalid empty package name"
toNixName n  = fromString (unPackageName n)

-- | Map library names specified in Cabal files to Nix package identifiers.
--
-- TODO: This list should not be hard-coded here; it belongs into the Nixpkgs
--       repository.
--
-- TODO: Re-use hook matching system from PostProcess.hs here.

libNixName :: String -> [Identifier]
libNixName ""                                   = []
libNixName "adns"                               = return "adns"
libNixName "alsa"                               = return "alsa-lib"
libNixName "alut"                               = return "freealut"
libNixName "appindicator-0.1"                   = return "libappindicator-gtk2"
libNixName "appindicator3-0.1"                  = return "libappindicator-gtk3"
libNixName "asound"                             = return "alsa-lib"
libNixName "ayatana-appindicator3-0.1"          = return "libayatana-appindicator"
libNixName "b2"                                 = return "libb2"
libNixName "boost_context"                      = return "boost"
libNixName "bz2"                                = return "bzip2"
libNixName "c++"                                = []  -- What is that?
libNixName "cairo-gobject"                      = return "cairo"
libNixName "cairo-pdf"                          = return "cairo"
libNixName "cairo-ps"                           = return "cairo"
libNixName "cairo-svg"                          = return "cairo"
libNixName "crypt"                              = return "libxcrypt" -- starting with NixOS 22.11, glibc's libcrypt will no longer be built
libNixName "crypto"                             = return "openssl"
libNixName "curses"                             = return "ncurses"
libNixName "dbusmenu-glib-0.4"                  = return "libdbusmenu"
libNixName "dbusmenu-gtk3-0.4"                  = ["libdbusmenu-gtk3", "gtk3"]
libNixName "dl"                                 = []  -- provided by glibc
libNixName "ff"                                 = return "libff"
libNixName "fftw3"                              = return "fftw"
libNixName "fftw3f"                             = return "fftwFloat"
libNixName "FLAC"                               = return "flac"
libNixName "freetype2"                          = return "freetype"
libNixName "gconf"                              = return "GConf"
libNixName "gconf-2.0"                          = return "GConf"
libNixName "gdk-2.0"                            = return "gtk2"
libNixName "gdk-3.0"                            = return "gtk3"
libNixName "gdk-pixbuf-2.0"                     = return "gdk-pixbuf"
libNixName "gdk-x11-2.0"                        = return "gdk_x11"
libNixName "geos_c"                             = return "geos"
libNixName "gdk-x11-3.0"                        = return "gtk3"
libNixName "gio-2.0"                            = return "glib"
libNixName "GL"                                 = return "libGL"
libNixName "GLEW"                               = return "glew"
libNixName "GLU"                                = ["libGLU","libGL"]
libNixName "glut"                               = ["freeglut","libGLU","libGL"]
libNixName "gmodule"                            = return "glib"
libNixName "gmodule-2.0"                        = return "glib"
libNixName "gnome-keyring"                      = return "libgnome-keyring"
libNixName "gnome-keyring-1"                    = return "libgnome-keyring"
libNixName "gnome-vfs-2.0"                      = return "gnome-vfs"
libNixName "gnome-vfs-module-2.0"               = return "gnome-vfs_module"
libNixName "gobject-2.0"                        = return "glib"
libNixName "gobject-introspection-1.0"          = return "gobject-introspection"
libNixName "graphene-gobject-1.0"               = return "graphene"
libNixName "gstreamer-audio-0.10"               = return "gst-plugins-base"
libNixName "gstreamer-audio-1.0"                = return "gst-plugins-base"
libNixName "gstreamer-base-0.10"                = return "gst-plugins-base"
libNixName "gstreamer-base-1.0"                 = return "gst-plugins-base"
libNixName "gstreamer-controller-0.10"          = return "gstreamer"
libNixName "gstreamer-dataprotocol-0.10"        = return "gstreamer"
libNixName "gstreamer-net-0.10"                 = return "gst-plugins-base"
libNixName "gstreamer-plugins-base-0.10"        = return "gst-plugins-base"
libNixName "gstreamer-video-1.0"                = return "gst-plugins-base"
libNixName "gthread-2.0"                        = return "glib"
libNixName "gtk+-2.0"                           = return "gtk2"
libNixName "gtk+-3.0"                           = return "gtk3"
libNixName "gtk-x11-2.0"                        = return "gtk_x11"
libNixName "gtk4-atspi"                         = return "gtk4"
libNixName "gtk4-broadway"                      = return "gtk4"
libNixName "gtk4"                               = return "gtk4"
libNixName "gtk4-unix-print"                    = return "gtk4"
libNixName "gtk4-wayland"                       = return "gtk4"
libNixName "gtk4-x11"                           = return "gtk4"
libNixName "gtksourceview-3.0"                  = return "gtksourceview3"
libNixName "gtksourceview-5"                    = return "gtksourceview5"
libNixName "harfbuzz-gobject"                   = return "harfbuzz"
libNixName "harfbuzz-subset"                    = return "harfbuzz"
libNixName "hidapi-libusb"                      = return "hidapi"
libNixName "icu-i18n"                           = return "icu"
libNixName "icu-io"                             = return "icu"
libNixName "icu-uc"                             = return "icu"
libNixName "icudata"                            = return "icu"
libNixName "icui18n"                            = return "icu"
libNixName "icuio"                              = return "icu"
libNixName "icuuc"                              = return "icu"
libNixName "idn"                                = return "libidn"
libNixName "IL"                                 = return "libdevil"
libNixName "ImageMagick"                        = return "imagemagick"
libNixName "Imlib2"                             = return "imlib2"
libNixName "iw"                                 = return "wirelesstools"
libNixName "jack"                               = return "libjack2"
libNixName "javascriptcoregtk"                  = return "webkitgtk"
libNixName "javascriptcoregtk-4.0"              = return "webkitgtk_4_0"
libNixName "javascriptcoregtk-4.1"              = return "webkitgtk_4_1"
libNixName "javascriptcoregtk-6.0"              = return "webkitgtk_6_0"
libNixName "jpeg"                               = return "libjpeg"
libNixName "jvm"                                = return "jdk"
libNixName "lapack"                             = return "liblapack"
libNixName "lber"                               = return "openldap"
libNixName "ldap"                               = return "openldap"
libNixName "libavutil"                          = return "ffmpeg"
libNixName "libbrotlienc"                       = return "brotli"
libNixName "libbrotlidec"                       = return "brotli"
libNixName "libcurl"                            = return "curl"
libNixName "libgsasl"                           = return "gsasl"
libNixName "liblzma"                            = return "xz"
libNixName "libnm"                              = return "networkmanager"
libNixName "libpcre"                            = return "pcre"
libNixName "libpcre2"                           = return "pcre2"
libNixName "libpcre2-8"                         = libNixName "libpcre2"
libNixName "libpipewire-0.3"                    = return "pipewire"
libNixName "libqrencode"                        = return "qrencode"
libNixName "libR"                               = return "R"
libNixName "libsecp256k1"                       = return "secp256k1"
libNixName "libsoup-2.4"                        = return "libsoup_2_4"
libNixName "libsoup-gnome-2.4"                  = return "libsoup_2_4"
libNixName "libsoup-3.0"                        = return "libsoup_3"
libNixName "libspa-0.2"                         = return "pipewire"
libNixName "libsystemd"                         = return "systemd"
libNixName "libudev"                            = return "systemd"
libNixName "libxml-2.0"                         = return "libxml2"
libNixName "libzip"                             = return "libzip"
libNixName "libzmq"                             = return "zeromq"
libNixName "liquid"                             = return "liquid-dsp"
libNixName "lzma"                               = return "xz"
libNixName "m"                                  = []  -- in stdenv
libNixName "magic"                              = return "file"
libNixName "MagickWand"                         = return "imagemagick"
libNixName "mnl"                                = return "libmnl"
libNixName "mpi"                                = return "openmpi"
libNixName "mysql"                              = return "mariadb"
libNixName "ncursesw"                           = return "ncurses"
libNixName "netsnmp"                            = return "net-snmp"
libNixName "nix-cmd"                            = return "nix"
libNixName "nix-expr-c"                         = return "nix"
libNixName "nix-expr"                           = return "nix"
libNixName "nix-fetchers-c"                     = return "nix"
libNixName "nix-fetchers"                       = return "nix"
libNixName "nix-flake-c"                        = return "nix"
libNixName "nix-flake"                          = return "nix"
libNixName "nix-main-c"                         = return "nix"
libNixName "nix-main"                           = return "nix"
libNixName "nix-store-c"                        = return "nix"
libNixName "nix-store"                          = return "nix"
libNixName "nix-util-c"                         = return "nix"
libNixName "nix-util"                           = return "nix"
libNixName "notify"                             = return "libnotify"
libNixName "odbc"                               = return "unixODBC"
libNixName "openblas"                           = return "openblasCompat"
libNixName "panelw"                             = return "ncurses"
libNixName "pangocairo"                         = return "pango"
libNixName "pcap"                               = return "libpcap"
libNixName "pfs-1.2"                            = return "pfstools"
libNixName "png"                                = return "libpng"
libNixName "poppler-glib"                       = return "poppler_gi"
libNixName "pq"                                 = return "libpq"
libNixName "pthread"                            = []
libNixName "pulse"                              = return "libpulseaudio"
libNixName "pulse-simple"                       = return "libpulseaudio"
libNixName "python-3.3"                         = return "python33"
libNixName "python-3.4"                         = return "python34"
libNixName "python3-embed"                      = return "python3"
libNixName "Qt5Core"                            = return "qt5"
libNixName "Qt5Gui"                             = return "qt5"
libNixName "Qt5Qml"                             = return "qt5"
libNixName "Qt5Quick"                           = return "qt5"
libNixName "Qt5Widgets"                         = return "qt5"
libNixName "quadprog"                           = return "QuadProgpp"
libNixName "rt"                                 = [] -- in glibc
libNixName "rtlsdr"                             = return "rtl-sdr"
libNixName "ruby1.8"                            = return "ruby"
libNixName "sass"                               = return "libsass"
libNixName "sctp"                               = return "lksctp-tools" -- This is linux-specific, we should create a common attribute if we ever add sctp support for other systems.
libNixName "sdl2"                               = return "SDL2"
libNixName "sndfile"                            = return "libsndfile"
libNixName "SoapySDR"                           = return "soapysdr"
libNixName "sodium"                             = return "libsodium"
libNixName "sqlite3"                            = return "sqlite"
libNixName "ssh2"                               = return "libssh2"
libNixName "ssl"                                = return "openssl"
libNixName "statgrab"                           = return "libstatgrab"
libNixName "stdc++"                             = [] -- What is that?
libNixName "stdc++.dll"                         = [] -- What is that?
libNixName "systemd-journal"                    = return "systemd"
libNixName "tag_c"                              = return "taglib"
libNixName "taglib_c"                           = return "taglib"
libNixName "tdjson"                             = return "tdlib"
libNixName "tensorflow"                         = return "libtensorflow"
libNixName "udev"                               = return "systemd";
libNixName "uuid"                               = return "libossp_uuid";
libNixName "vte-2.91"                           = return "vte_291"
libNixName "vulkan"                             = return "vulkan-loader"
libNixName "wayland-client"                     = return "wayland"
libNixName "wayland-cursor"                     = return "wayland"
libNixName "wayland-egl"                        = return "libGL"
libNixName "wayland-server"                     = return "wayland"
libNixName "webkit"                             = return "webkitgtk" -- this is an alias, so it only works for downstream expressions not in hackage-packages.nix
libNixName "webkit2gtk"                         = return "webkitgtk"
libNixName "webkit2gtk-4.0"                     = return "webkitgtk_4_0"
libNixName "webkit2gtk-4.1"                     = return "webkitgtk_4_1"
libNixName "webkit2gtk-6.0"                     = return "webkitgtk_6_0"
libNixName "webkit2gtk-web-extension-4.0"       = return "webkitgtk_4_0"
libNixName "webkit2gtk-web-extension-4.1"       = return "webkitgtk_4_1"
libNixName "webkit2gtk-web-extension-6.0"       = return "webkitgtk_6_0"
libNixName "wxGTK"                              = return "wxGTK32"
libNixName "X11"                                = return "libX11"
libNixName "x11"                                = return "libX11"
libNixName "xau"                                = return "libXau"
libNixName "Xcursor"                            = return "libXcursor"
libNixName "xerces-c"                           = return "xercesc"
libNixName "Xext"                               = return "libXext"
libNixName "xft"                                = return "libXft"
libNixName "Xi"                                 = return "libXi"
libNixName "Xinerama"                           = return "libXinerama"
libNixName "xkbcommon"                          = return "libxkbcommon"
libNixName "xml2"                               = return "libxml2"
libNixName "Xpm"                                = return "libXpm"
libNixName "Xrandr"                             = return "libXrandr"
libNixName "Xrender"                            = return "libXrender"
libNixName "xscrnsaver"                         = return "libXScrnSaver"
libNixName "Xss"                                = return "libXScrnSaver"
libNixName "Xtst"                               = return "libXtst"
libNixName "Xxf86vm"                            = return "libXxf86vm"
libNixName "yaml"                               = return "libyaml"
libNixName "yaml-0.1"                           = return "libyaml"
libNixName "z"                                  = return "zlib"
libNixName "zmq"                                = return "zeromq"
libNixName "TKBO"                               = return "opencascade-occt"
libNixName "TKBRep"                             = return "opencascade-occt"
libNixName "TKBin"                              = return "opencascade-occt"
libNixName "TKBinL"                             = return "opencascade-occt"
libNixName "TKBinTObj"                          = return "opencascade-occt"
libNixName "TKBinXCAF"                          = return "opencascade-occt"
libNixName "TKBool"                             = return "opencascade-occt"
libNixName "TKCAF"                              = return "opencascade-occt"
libNixName "TKCDF"                              = return "opencascade-occt"
libNixName "TKDCAF"                             = return "opencascade-occt"
libNixName "TKDE"                               = return "opencascade-occt"
libNixName "TKDECascade"                        = return "opencascade-occt"
libNixName "TKDEGLTF"                           = return "opencascade-occt"
libNixName "TKDEIGES"                           = return "opencascade-occt"
libNixName "TKDEOBJ"                            = return "opencascade-occt"
libNixName "TKDEPLY"                            = return "opencascade-occt"
libNixName "TKDESTEP"                           = return "opencascade-occt"
libNixName "TKDESTL"                            = return "opencascade-occt"
libNixName "TKDEVRML"                           = return "opencascade-occt"
libNixName "TKDraw"                             = return "opencascade-occt"
libNixName "TKExpress"                          = return "opencascade-occt"
libNixName "TKFeat"                             = return "opencascade-occt"
libNixName "TKFillet"                           = return "opencascade-occt"
libNixName "TKG2d"                              = return "opencascade-occt"
libNixName "TKG3d"                              = return "opencascade-occt"
libNixName "TKGeomAlgo"                         = return "opencascade-occt"
libNixName "TKGeomBase"                         = return "opencascade-occt"
libNixName "TKHLR"                              = return "opencascade-occt"
libNixName "TKLCAF"                             = return "opencascade-occt"
libNixName "TKMath"                             = return "opencascade-occt"
libNixName "TKMesh"                             = return "opencascade-occt"
libNixName "TKMeshVS"                           = return "opencascade-occt"
libNixName "TKOffset"                           = return "opencascade-occt"
libNixName "TKOpenGl"                           = return "opencascade-occt"
libNixName "TKOpenGlTest"                       = return "opencascade-occt"
libNixName "TKPrim"                             = return "opencascade-occt"
libNixName "TKQADraw"                           = return "opencascade-occt"
libNixName "TKRWMesh"                           = return "opencascade-occt"
libNixName "TKService"                          = return "opencascade-occt"
libNixName "TKShHealing"                        = return "opencascade-occt"
libNixName "TKStd"                              = return "opencascade-occt"
libNixName "TKStdL"                             = return "opencascade-occt"
libNixName "TKTObj"                             = return "opencascade-occt"
libNixName "TKTObjDRAW"                         = return "opencascade-occt"
libNixName "TKTopAlgo"                          = return "opencascade-occt"
libNixName "TKTopTest"                          = return "opencascade-occt"
libNixName "TKV3d"                              = return "opencascade-occt"
libNixName "TKVCAF"                             = return "opencascade-occt"
libNixName "TKViewerTest"                       = return "opencascade-occt"
libNixName "TKXCAF"                             = return "opencascade-occt"
libNixName "TKXDEDRAW"                          = return "opencascade-occt"
libNixName "TKXMesh"                            = return "opencascade-occt"
libNixName "TKXSBase"                           = return "opencascade-occt"
libNixName "TKXSDRAW"                           = return "opencascade-occt"
libNixName "TKXSDRAWDE"                         = return "opencascade-occt"
libNixName "TKXSDRAWGLTF"                       = return "opencascade-occt"
libNixName "TKXSDRAWIGES"                       = return "opencascade-occt"
libNixName "TKXSDRAWOBJ"                        = return "opencascade-occt"
libNixName "TKXSDRAWPLY"                        = return "opencascade-occt"
libNixName "TKXSDRAWSTEP"                       = return "opencascade-occt"
libNixName "TKXSDRAWSTL"                        = return "opencascade-occt"
libNixName "TKXSDRAWVRML"                       = return "opencascade-occt"
libNixName "TKXml"                              = return "opencascade-occt"
libNixName "TKXmlL"                             = return "opencascade-occt"
libNixName "TKXmlTObj"                          = return "opencascade-occt"
libNixName "TKXmlXCAF"                          = return "opencascade-occt"
libNixName "TKernel"                            = return "opencascade-occt"
libNixName x                                    = return (guessNixIdentifier x)

-- | Map build tool names to Nix attribute names.
buildToolNixName :: String -> [Identifier]
buildToolNixName ""                             = return (error "buildToolNixName: invalid empty dependency name")
buildToolNixName "cabal"                        = return "cabal-install"
buildToolNixName "fltk-config"                  = return "fltk"
buildToolNixName "ghc"                          = []
buildToolNixName "gtk2hsC2hs"                   = return "gtk2hs-buildtools"
buildToolNixName "gtk2hsHookGenerator"          = return "gtk2hs-buildtools"
buildToolNixName "gtk2hsTypeGen"                = return "gtk2hs-buildtools"
buildToolNixName "hsc2hs"                       = []
buildToolNixName "nix-build"                    = return "nix"
buildToolNixName "nix-env"                      = return "nix"
buildToolNixName "nix-hash"                     = return "nix"
buildToolNixName "nix-instantiate"              = return "nix"
buildToolNixName "nix-store"                    = return "nix"
buildToolNixName "utillinux"                    = return "util-linux"
buildToolNixName x                              = return (fromString x)

-- | Helper function to extract the package name from a String that may or may
-- not be formatted like a Cabal package identifier.
--
-- >>> guessNixIdentifier "foo-1.0"
-- Identifier "foo"
-- >>> guessNixIdentifier "foo"
-- Identifier "foo"
-- >>> guessNixIdentifier "foo - 0"
-- Identifier "foo - 0"
-- >>> guessNixIdentifier "1foo-1.0"
-- Identifier "1foo"
-- >>> guessNixIdentifier "-foo-1.0"
-- Identifier "-foo-1.0"

guessNixIdentifier :: String -> Identifier
guessNixIdentifier x = fromString (fromMaybe x maybePackageId)
  where
    maybePackageId = unPackageName . pkgName <$> simpleParse x
